import SwiftUI
import UIKit

struct AppBackground: View { var body: some View { LinearGradient(colors: [Color(uiColor: .systemGroupedBackground), Color.indigo.opacity(0.07)], startPoint: .topLeading, endPoint: .bottomTrailing).ignoresSafeArea() } }
extension View { func glassCard() -> some View { self.background(.ultraThinMaterial, in: RoundedRectangle(cornerRadius: 18, style: .continuous)).overlay { RoundedRectangle(cornerRadius: 18, style: .continuous).strokeBorder(.white.opacity(0.28), lineWidth: 0.7) }.shadow(color: .black.opacity(0.08), radius: 12, y: 5) } }
struct StatusBadge: View { let status: ActivityStatus; var body: some View { Text(status.title).font(.caption2.weight(.bold)).foregroundStyle(color).padding(.horizontal, 8).padding(.vertical, 4).background(color.opacity(0.13), in: Capsule()) }; var color: Color { switch status { case .new: .blue; case .scheduled: .indigo; case .quoted: .purple; case .approved: .teal; case .inProgress: .orange; case .waiting: .yellow; case .completed, .paid: .green; case .cancelled: .red } } }
struct DashboardWidget<Content: View>: View { let title: String; let subtitle: String; let icon: String; let accent: Color; @ViewBuilder var content: Content; var body: some View { VStack(alignment: .leading, spacing: 12) { HStack { Image(systemName: icon).foregroundStyle(accent); VStack(alignment: .leading) { Text(title).font(.headline); Text(subtitle).font(.caption).foregroundStyle(.secondary) }; Spacer() }; content }.padding().glassCard() } }
struct MetricCard: View { let value: String; let label: String; let symbol: String; let color: Color; var body: some View { VStack(alignment: .leading, spacing: 8) { Image(systemName: symbol).foregroundStyle(color); Text(value).font(.title3.bold()).lineLimit(1).minimumScaleFactor(0.7); Text(label).font(.caption).foregroundStyle(.secondary) }.frame(maxWidth: .infinity, alignment: .leading).padding().glassCard() } }
struct CompactRow: View { let title: String; let detail: String; let symbol: String; var body: some View { HStack { Image(systemName: symbol).foregroundStyle(.secondary).frame(width: 20); Text(title).lineLimit(1); Spacer(); Text(detail).font(.caption).foregroundStyle(.secondary) }.font(.subheadline) } }
struct ClientRow: View { let client: Client; var body: some View { HStack(spacing: 12) { Text(client.name.prefix(1).uppercased()).font(.headline).foregroundStyle(.white).frame(width: 42, height: 42).background(LinearGradient(colors: [.indigo, .cyan], startPoint: .topLeading, endPoint: .bottomTrailing), in: Circle()); VStack(alignment: .leading, spacing: 3) { HStack { Text(client.name).font(.headline); if client.isFavorite { Image(systemName: "star.fill").font(.caption).foregroundStyle(.yellow) } }; Text(client.company.isEmpty ? client.phone : client.company).font(.subheadline).foregroundStyle(.secondary) }; Spacer(); Image(systemName: "chevron.right").font(.caption.weight(.bold)).foregroundStyle(.tertiary) }.padding(.vertical, 5) } }
struct ActivityRow: View { let record: ActivityRecord; var body: some View { HStack { Image(systemName: icon).foregroundStyle(.indigo).frame(width: 24); VStack(alignment: .leading) { Text(record.title).font(.subheadline.weight(.medium)); Text(record.client?.name ?? record.employee).font(.caption).foregroundStyle(.secondary) }; Spacer(); Text(record.date.formatted(date: .omitted, time: .shortened)).font(.caption2).foregroundStyle(.secondary) } }; var icon: String { switch record.type { case "Appointment": "calendar"; case "Invoice": "receipt"; case "Estimate": "doc.text"; case "Note": "note.text"; default: "bolt.fill" } } }
struct ActivityCard: View { let record: ActivityRecord; @State private var expanded = false; var body: some View { Button { withAnimation(.snappy) { expanded.toggle() } } label: { VStack(alignment: .leading, spacing: 10) { HStack(alignment: .top) { Image(systemName: record.type == "Appointment" ? "calendar" : "bolt.fill").foregroundStyle(.indigo).frame(width: 28, height: 28).background(.indigo.opacity(0.12), in: Circle()); VStack(alignment: .leading, spacing: 4) { Text(record.title).font(.headline); Text("\(record.client?.name ?? "Workspace") · \(record.employee)").font(.caption).foregroundStyle(.secondary) }; Spacer(); StatusBadge(status: record.status) }; HStack { Text(record.date.formatted(date: .abbreviated, time: .shortened)).font(.caption).foregroundStyle(.secondary); Spacer(); Image(systemName: expanded ? "chevron.up" : "chevron.down").font(.caption).foregroundStyle(.secondary) }; if expanded { Divider(); Text(record.detail.isEmpty ? "No additional details were recorded." : record.detail).font(.subheadline).foregroundStyle(.secondary).frame(maxWidth: .infinity, alignment: .leading) } }.padding().glassCard() }.buttonStyle(.plain).listRowBackground(Color.clear).listRowSeparator(.hidden).padding(.vertical, 3) } }
struct AppointmentRow: View { let appointment: Appointment; var body: some View { HStack(spacing: 12) { Text(appointment.startDate.formatted(date: .omitted, time: .shortened)).font(.caption.bold()).multilineTextAlignment(.center).foregroundStyle(.indigo).frame(width: 62); VStack(alignment: .leading) { Text(appointment.title).font(.headline); Text(appointment.client?.name ?? "Unassigned").font(.caption).foregroundStyle(.secondary) }; Spacer(); StatusBadge(status: appointment.status) }.padding(.vertical, 4) } }
struct EmptyState: View { let symbol: String; let title: String; let detail: String; var body: some View { ContentUnavailableView { Label(title, systemImage: symbol) } description: { Text(detail) } } }
struct FilterChip: View { let title: String; let active: Bool; let action: () -> Void; var body: some View { Button(title, action: action).font(.caption.weight(.semibold)).padding(.horizontal, 12).padding(.vertical, 7).background(active ? Color.indigo : Color.secondary.opacity(0.12), in: Capsule()).foregroundStyle(active ? .white : .primary) } }
struct MediaAttachmentPreview: View { let attachment: MediaAttachment; var body: some View { Group { if attachment.mediaType == CapturedMediaType.photo.rawValue, let image = UIImage(data: attachment.data) { Image(uiImage: image).resizable().scaledToFill() } else { Image(systemName: "video.fill").font(.title2).foregroundStyle(.indigo).frame(maxWidth: .infinity, maxHeight: .infinity).background(.indigo.opacity(0.12)) } }.frame(width: 88, height: 88).clipShape(RoundedRectangle(cornerRadius: 14, style: .continuous)) } }
struct ClientAvatar: View { let client: Client; let size: CGFloat; var body: some View { Group { if let data = client.profileImageData, let image = UIImage(data: data) { Image(uiImage: image).resizable().scaledToFill() } else { Text(client.name.prefix(1).uppercased()).font(.system(size: size * 0.42, weight: .bold)).foregroundStyle(.white).frame(maxWidth: .infinity, maxHeight: .infinity).background(LinearGradient(colors: [.indigo, .cyan], startPoint: .topLeading, endPoint: .bottomTrailing)) } }.frame(width: size, height: size).clipShape(Circle()) } }
