import Foundation
import SwiftData
import Observation

enum ActivityStatus: String, Codable, CaseIterable { case new, scheduled, quoted, approved, inProgress, waiting, completed, paid, cancelled; var title: String { self == .inProgress ? "In Progress" : rawValue.capitalized } }
enum DocumentKind: String, Codable { case estimate, invoice }
@Model final class Client { @Attribute(.unique) var id: UUID; var name: String; var company: String; var email: String; var phone: String; var address: String; var notes: String; var isFavorite: Bool; @Attribute(.externalStorage) var profileImageData: Data?; var createdAt: Date; var lastActivityAt: Date; @Relationship(deleteRule: .cascade, inverse: \ActivityRecord.client) var activities: [ActivityRecord] = []; @Relationship(deleteRule: .cascade, inverse: \Appointment.client) var appointments: [Appointment] = []; @Relationship(deleteRule: .cascade, inverse: \CRMNote.client) var clientNotes: [CRMNote] = []; @Relationship(deleteRule: .cascade, inverse: \CRMTask.client) var tasks: [CRMTask] = []; @Relationship(deleteRule: .cascade, inverse: \FinancialDocument.client) var documents: [FinancialDocument] = []; @Relationship(deleteRule: .cascade, inverse: \MediaAttachment.client) var media: [MediaAttachment] = []; init(name: String, company: String = "", email: String = "", phone: String = "", address: String = "", notes: String = "", isFavorite: Bool = false) { id = UUID(); self.name = name; self.company = company; self.email = email; self.phone = phone; self.address = address; self.notes = notes; self.isFavorite = isFavorite; createdAt = .now; lastActivityAt = .now } }
@Model final class ActivityRecord { @Attribute(.unique) var id: UUID; var title: String; var detail: String; var date: Date; var employee: String; var statusRaw: String; var type: String; var relatedAppointmentID: UUID?; var client: Client?; var status: ActivityStatus { ActivityStatus(rawValue: statusRaw) ?? .new }; init(title: String, detail: String, date: Date = .now, employee: String = "You", status: ActivityStatus = .new, type: String, relatedAppointmentID: UUID? = nil, client: Client? = nil) { id = UUID(); self.title = title; self.detail = detail; self.date = date; self.employee = employee; statusRaw = status.rawValue; self.type = type; self.relatedAppointmentID = relatedAppointmentID; self.client = client } }
@Model final class Appointment { @Attribute(.unique) var id: UUID; var title: String; var details: String; var startDate: Date; var endDate: Date; var statusRaw: String; var client: Client?; var status: ActivityStatus { ActivityStatus(rawValue: statusRaw) ?? .scheduled }; init(title: String, details: String = "", startDate: Date, endDate: Date, status: ActivityStatus = .scheduled, client: Client? = nil) { id = UUID(); self.title = title; self.details = details; self.startDate = startDate; self.endDate = endDate; statusRaw = status.rawValue; self.client = client } }
@Model final class CRMNote { @Attribute(.unique) var id: UUID; var body: String; var createdAt: Date; var client: Client?; init(body: String, client: Client? = nil) { id = UUID(); self.body = body; createdAt = .now; self.client = client } }
@Model final class CRMTask { @Attribute(.unique) var id: UUID; var title: String; var dueDate: Date; var isComplete: Bool; var client: Client?; init(title: String, dueDate: Date, isComplete: Bool = false, client: Client? = nil) { id = UUID(); self.title = title; self.dueDate = dueDate; self.isComplete = isComplete; self.client = client } }
@Model final class FinancialDocument { @Attribute(.unique) var id: UUID; var title: String; var kindRaw: String; var statusRaw: String; var issuedAt: Date; var updatedAt: Date; var client: Client?; @Relationship(deleteRule: .cascade, inverse: \LineItem.document) var lineItems: [LineItem] = []; var kind: DocumentKind { DocumentKind(rawValue: kindRaw) ?? .estimate }; var status: ActivityStatus { ActivityStatus(rawValue: statusRaw) ?? .new }; var total: Double { lineItems.reduce(0) { $0 + $1.quantity * $1.unitPrice } }; init(title: String, kind: DocumentKind, status: ActivityStatus, client: Client? = nil) { id = UUID(); self.title = title; kindRaw = kind.rawValue; statusRaw = status.rawValue; issuedAt = .now; updatedAt = .now; self.client = client } }
@Model final class LineItem { @Attribute(.unique) var id: UUID; var itemDescription: String; var quantity: Double; var unitPrice: Double; var document: FinancialDocument?; init(itemDescription: String, quantity: Double, unitPrice: Double, document: FinancialDocument? = nil) { id = UUID(); self.itemDescription = itemDescription; self.quantity = quantity; self.unitPrice = unitPrice; self.document = document } }
@Model final class MediaAttachment { @Attribute(.unique) var id: UUID; var name: String; var mediaType: String; @Attribute(.externalStorage) var data: Data; var createdAt: Date; var client: Client?; init(name: String, mediaType: String, data: Data, client: Client? = nil) { id = UUID(); self.name = name; self.mediaType = mediaType; self.data = data; createdAt = .now; self.client = client } }
protocol CRMService { func sync() async throws }
@Observable final class LocalCRMService: CRMService { func sync() async throws {} }
enum Currency { static func format(_ value: Double) -> String { value.formatted(.currency(code: Locale.current.currency?.identifier ?? "USD")) } }
