import SwiftUI
import SwiftData

enum ActivityLogger { static func log(_ title: String, detail: String, type: String, status: ActivityStatus, relatedAppointmentID: UUID? = nil, client: Client?, in context: ModelContext) { let activity = ActivityRecord(title: title, detail: detail, status: status, type: type, relatedAppointmentID: relatedAppointmentID, client: client); context.insert(activity); client?.lastActivityAt = .now } }

struct QuickCreateSheet: View {
    @Environment(\.dismiss) private var dismiss; @Environment(\.modelContext) private var context
    @Query(sort: \Client.name) private var clients: [Client]
    let action: QuickAction; let fixedClient: Client?
    @State private var title = ""; @State private var company = ""; @State private var email = ""; @State private var phone = ""; @State private var address = ""; @State private var bodyText = ""; @State private var date = Date.now; @State private var endDate = Date.now.addingTimeInterval(3600); @State private var selectedClientID: UUID?; @State private var kind: DocumentKind = .estimate; @State private var status: ActivityStatus = .new; @State private var lineItems = [DraftLine(description: "", quantity: 1, price: 0)]; @State private var capturedMedia: CapturedMedia?; @State private var captureSource: CaptureSource?
    init(action: QuickAction, fixedClient: Client? = nil) { self.action = action; self.fixedClient = fixedClient; _kind = State(initialValue: action == .invoice ? .invoice : .estimate) }
    private var selectedClient: Client? { fixedClient ?? clients.first { $0.id == selectedClientID } }
    var body: some View { NavigationStack { Form { if fixedClient == nil && action != .client { Section("Client") { Picker("For", selection: $selectedClientID) { Text("No client yet").tag(UUID?.none); ForEach(clients) { Text($0.name).tag(Optional($0.id)) } } } }
        switch action { case .client: clientFields; case .appointment: appointmentFields; case .note: noteFields; case .task: taskFields; case .estimate, .invoice: documentFields; case .media: mediaFields }
    }.navigationTitle("New \(action.title)").navigationBarTitleDisplayMode(.inline).toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button("Save", action: save).fontWeight(.semibold).disabled(!canSave) } }.fullScreenCover(item: $captureSource) { CameraCapturePicker(source: $0, media: $capturedMedia) } } }
    @ViewBuilder private var clientFields: some View { Section("Contact") { TextField("Client name", text: $title); TextField("Company", text: $company); TextField("Email", text: $email).textInputAutocapitalization(.never).keyboardType(.emailAddress); TextField("Phone", text: $phone).keyboardType(.phonePad) }; Section("Location & notes") { TextField("Address", text: $address); TextEditor(text: $bodyText).frame(minHeight: 90).overlay(alignment: .topLeading) { if bodyText.isEmpty { Text("Notes").foregroundStyle(.tertiary).padding(.top, 8).allowsHitTesting(false) } } } }
    @ViewBuilder private var appointmentFields: some View { Section("Appointment") { TextField("Title", text: $title); DatePicker("Starts", selection: $date); DatePicker("Ends", selection: $endDate); Picker("Status", selection: $status) { ForEach(ActivityStatus.allCases, id: \.self) { Text($0.title).tag($0) } } }; Section("Details") { TextEditor(text: $bodyText).frame(minHeight: 100) } }
    @ViewBuilder private var noteFields: some View { Section("Note") { TextEditor(text: $bodyText).frame(minHeight: 180) } }
    @ViewBuilder private var taskFields: some View { Section("Task") { TextField("What needs to be done?", text: $title); DatePicker("Due", selection: $date, displayedComponents: [.date, .hourAndMinute]) } }
    @ViewBuilder private var documentFields: some View { Section("Document") { Picker("Type", selection: $kind) { Text("Estimate").tag(DocumentKind.estimate); Text("Invoice").tag(DocumentKind.invoice) }; TextField("Title", text: $title); Picker("Status", selection: $status) { ForEach(ActivityStatus.allCases, id: \.self) { Text($0.title).tag($0) } } }; Section("Line items") { ForEach($lineItems) { $line in HStack { TextField("Description", text: $line.description); TextField("Qty", value: $line.quantity, format: .number).keyboardType(.decimalPad).frame(width: 48); TextField("Price", value: $line.price, format: .currency(code: Locale.current.currency?.identifier ?? "USD")).keyboardType(.decimalPad).frame(width: 80) } }.onDelete { lineItems.remove(atOffsets: $0) }; Button("Add line item", systemImage: "plus") { lineItems.append(DraftLine(description: "", quantity: 1, price: 0)) }; HStack { Spacer(); Text("Total  \(Currency.format(lineItems.reduce(0) { $0 + $1.quantity * $1.price }))").fontWeight(.semibold) } } }
    @ViewBuilder private var mediaFields: some View { Section("Add media") { if let capturedMedia { Label(capturedMedia.type == .video ? "Video ready to attach" : "Photo ready to attach", systemImage: capturedMedia.type == .video ? "video.fill" : "photo.fill").foregroundStyle(.green) }; Button(capturedMedia == nil ? "Take Photo or Video" : "Retake", systemImage: "camera.fill") { captureSource = .camera }.fontWeight(.semibold); Button("Choose from Library", systemImage: "photo.on.rectangle") { captureSource = .library }.fontWeight(.semibold); Text("Attach a new capture or an existing photo or video from the camera roll. Media stays on this device until sync is available.").font(.caption).foregroundStyle(.secondary) } }
    private var canSave: Bool { switch action { case .note: !bodyText.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty; case .media: capturedMedia != nil && selectedClient != nil; default: !title.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty } }
    private func save() { switch action {
        case .client: let client = Client(name: title, company: company, email: email, phone: phone, address: address, notes: bodyText); context.insert(client); ActivityLogger.log("Client created", detail: "Added \(client.name) to CrewCrate.", type: "Client", status: .new, client: client, in: context)
        case .appointment: let item = Appointment(title: title, details: bodyText, startDate: date, endDate: endDate, status: status, client: selectedClient); context.insert(item); ActivityLogger.log("Appointment scheduled", detail: "\(title) · \(date.formatted(date: .abbreviated, time: .shortened))", type: "Appointment", status: status, relatedAppointmentID: item.id, client: selectedClient, in: context)
        case .note: let note = CRMNote(body: bodyText, client: selectedClient); context.insert(note); ActivityLogger.log("Note added", detail: bodyText, type: "Note", status: .new, client: selectedClient, in: context)
        case .task: let task = CRMTask(title: title, dueDate: date, client: selectedClient); context.insert(task); ActivityLogger.log("Task created", detail: title, type: "Task", status: .inProgress, client: selectedClient, in: context)
        case .estimate, .invoice: let doc = FinancialDocument(title: title, kind: kind, status: status, client: selectedClient); context.insert(doc); lineItems.filter { !$0.description.isEmpty }.forEach { context.insert(LineItem(itemDescription: $0.description, quantity: $0.quantity, unitPrice: $0.price, document: doc)) }; ActivityLogger.log("\(kind.rawValue.capitalized) created", detail: "\(title) · \(Currency.format(doc.total))", type: kind.rawValue.capitalized, status: status, client: selectedClient, in: context)
        case .media: if let capturedMedia, let client = selectedClient { let attachment = MediaAttachment(name: capturedMedia.type == .video ? "Captured video" : "Captured photo", mediaType: capturedMedia.type.rawValue, data: capturedMedia.data, client: client); context.insert(attachment); ActivityLogger.log("\(capturedMedia.type == .video ? "Video" : "Photo") attached", detail: "Added media to \(client.name).", type: "Media", status: .new, client: client, in: context) }
        }; dismiss() }
}
struct AppointmentEditor: View { @Environment(\.dismiss) private var dismiss; @Bindable var appointment: Appointment; let activities: [ActivityRecord]; @State private var originalTitle: String
    init(appointment: Appointment, activities: [ActivityRecord]) { self.appointment = appointment; self.activities = activities; _originalTitle = State(initialValue: appointment.title) }
    var body: some View { NavigationStack { Form { Section("Appointment") { TextField("Title", text: $appointment.title); DatePicker("Starts", selection: $appointment.startDate); DatePicker("Ends", selection: $appointment.endDate); Picker("Status", selection: $appointment.statusRaw) { ForEach(ActivityStatus.allCases, id: \.self) { Text($0.title).tag($0.rawValue) } } }; Section("Details") { TextEditor(text: $appointment.details).frame(minHeight: 120) } }.navigationTitle("Edit Appointment").toolbar { ToolbarItem(placement: .cancellationAction) { Button("Cancel") { dismiss() } }; ToolbarItem(placement: .confirmationAction) { Button("Save") { updateActivity(); dismiss() }.fontWeight(.semibold) } } } }
    private func updateActivity() { let matching = activities.filter { $0.relatedAppointmentID == appointment.id || ($0.type == "Appointment" && $0.client?.id == appointment.client?.id && $0.detail.localizedCaseInsensitiveContains(originalTitle)) }; matching.forEach { $0.title = "Appointment updated"; $0.detail = "\(appointment.title) · \(appointment.startDate.formatted(date: .abbreviated, time: .shortened))"; $0.date = appointment.startDate; $0.statusRaw = appointment.statusRaw; $0.relatedAppointmentID = appointment.id } }
}
struct DraftLine: Identifiable { let id = UUID(); var description: String; var quantity: Double; var price: Double }

struct ClientEditor: View { @Environment(\.dismiss) private var dismiss; @Bindable var client: Client; var body: some View { NavigationStack { Form { Section("Contact") { TextField("Client name", text: $client.name); TextField("Company", text: $client.company); TextField("Email", text: $client.email); TextField("Phone", text: $client.phone) }; Section("Details") { TextField("Address", text: $client.address); TextEditor(text: $client.notes).frame(minHeight: 120); Toggle("Favorite client", isOn: $client.isFavorite) } }.navigationTitle("Edit Client").toolbar { ToolbarItem(placement: .confirmationAction) { Button("Done") { dismiss() } } } } } }

enum SeedData { static func installIfNeeded(in context: ModelContext, existingClients: [Client]) { guard existingClients.isEmpty else { return }; let ava = Client(name: "Ava Mitchell", company: "Mitchell Homeworks", email: "ava@mitchellhomeworks.com", phone: "(512) 555-0148", address: "2100 South Lamar Blvd, Austin, TX", isFavorite: true); let eli = Client(name: "Eli Rodriguez", company: "Rodriguez Properties", email: "eli@rodriguezproperties.com", phone: "(512) 555-0187", address: "804 W 24th Street, Austin, TX"); context.insert(ava); context.insert(eli); let appointment = Appointment(title: "Kitchen walkthrough", details: "Confirm cabinet measurements and finish selections.", startDate: Calendar.current.date(bySettingHour: 10, minute: 0, second: 0, of: .now) ?? .now, endDate: Calendar.current.date(byAdding: .hour, value: 1, to: .now) ?? .now, client: ava); context.insert(appointment); let invoice = FinancialDocument(title: "INV-1042 · Kitchen deposit", kind: .invoice, status: .waiting, client: ava); context.insert(invoice); context.insert(LineItem(itemDescription: "Kitchen renovation deposit", quantity: 1, unitPrice: 2400, document: invoice)); let estimate = FinancialDocument(title: "EST-203 · Exterior paint", kind: .estimate, status: .quoted, client: eli); context.insert(estimate); context.insert(LineItem(itemDescription: "Exterior painting", quantity: 1, unitPrice: 3850, document: estimate)); let task = CRMTask(title: "Send finish options", dueDate: .now.addingTimeInterval(86_400), client: ava); context.insert(task); ActivityLogger.log("Invoice sent", detail: "INV-1042 · Kitchen deposit", type: "Invoice", status: .waiting, client: ava, in: context); ActivityLogger.log("Estimate sent", detail: "EST-203 · Exterior paint", type: "Estimate", status: .quoted, client: eli, in: context); ActivityLogger.log("Appointment scheduled", detail: "Kitchen walkthrough tomorrow at 10:00 AM.", type: "Appointment", status: .scheduled, relatedAppointmentID: appointment.id, client: ava, in: context) } }
